MODULES = nominatim
PGXS := /usr/lib/postgresql/9.3/lib/pgxs/src/makefiles/pgxs.mk
PG_CONFIG := /usr/bin/pg_config
include $(PGXS)

all:
	chmod 755 nominatim.so

install:
	@echo Library does not need to be installed.
